apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  API_PORT: "3000"
  DB: "node_app"
  DBHOST: "terraform-20240709093755987300000001.c98iq2wsq66l.ap-south-1.rds.amazonaws.com"
  DBPORT: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-test-api
  labels:
    app: node-test-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-test-api
  template:
    metadata:
      labels:
        app: node-test-api
    spec:
      containers:
      - name: node-test-api
        imagePullPolicy: Always
        image: soumyaparida00/node-test-api:latest
        envFrom:
        - configMapRef:
            name: api-config
        - secretRef:
            name: api-secret
        ports:
        - containerPort: 3000
