---
apiVersion: v1
kind: Service
metadata:
  name: node-test-api
spec:
  selector:
    app: node-test-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  # Exposes the service to an external load balancer
